### ISSUE TITLE
Dublicates in yaml file ignored silently by StationConfig

### ISSUE THREAD

**Issue by ThorvaldLarsen** [qdev-dk/qdev-wrappers#110]
With many instruments the .yaml file can get quite long and the possibility for mistakes fairly high over time. Recently had two instruments in the .yaml file duplicated without any errors.

Currently the code ignores the first one in the .yaml file and initialises with the last entry of a given name.

I propose that a check is added to the station configurator such that an error is raised if not all entries in the .yaml file have unique names.

@Dominik-Vogel

**Comment by jenshnielsen** [comment]
It looks like this is a "feature" of pyyaml. see https://stackoverflow.com/questions/44904290/getting-duplicate-keys-in-yaml-using-python Perhaps we should switch to [ruamel.yaml](https://pypi.org/project/ruamel.yaml/)

**Comment by ThorvaldLarsen** [comment]
This seems like a good idea. This would also support scientific notation for floats according to this https://stackoverflow.com/questions/30458977/yaml-loads-5e-6-as-string-and-not-a-number.

Are there any downsides to russel.yaml? From a quick search it looks to be an enhanced version of pyyaml.

**Comment by jenshnielsen** [comment]
Cool, I don't think there are any downsides other than the name being a bit odd.
