### ISSUE TITLE
Station configurator - channels

### ISSUE THREAD

**Issue by nataliejpg** [qdev-dk/qdev-wrappers#127]
@Dominik-Vogel Was wondering what your thoughts are about how to handle channels in the station configurator, maybe there could be a nicer way than the current on where you have to dig into the parameters by name?

**Comment by ThorvaldLarsen** [comment]
Do you have something else specific in mind? It is not that I think the current way is perfect but I have a hard time coming up with a better way to do it - in the end you have to modify the parameter.

**Comment by nataliejpg** [comment]
yh true, i think I did at the time but reading back this just seems really low priority, Let's close and I'll reopen and expand if my initial thought comes back to me.
