### ISSUE TITLE
Refactor common code in show_num

### ISSUE THREAD

**Issue by ThorvaldLarsen** [qdev-dk/qdev-wrappers#34]

**Comment by nataliejpg** [comment]
@ThorvaldLarsen do you know if the bug that Anders mentioned on slack get investigated/fixed?

**Comment by ThorvaldLarsen** [comment]
Yes, it was fixed by #64. Working well on T3 and T11 with the current version.

**Comment by ThorvaldLarsen** [comment]
Closing as we will soon move to new dataset and leave show_num behind
