### ISSUE TITLE
Make all-wrappers master branch

### ISSUE THREAD

**Issue by ThorvaldLarsen** [qdev-dk/qdev-wrappers#35]

**Comment by ThorvaldLarsen** [comment]
@Dominik-Vogel Any chance this can happen? There hasn't been any changes to the master branch since october so I think we can safely assume that no one is using it.

Also, not sure if all-wrappers should 'become' master or be merged into master.
Maybe @nataliejpg has an opinion on this as I think you made this repository.

**Comment by Dominik-Vogel** [comment]
I think the only reason why this has not happened yet is that there have been more pressing issues, that made a functional difference. I think we can merge this branch into master. At the same time we will have to migrate the issues and pull requests. I have a feeling they will not become less, so it is probably good to do it early.

**Comment by jenshnielsen** [comment]
I suggest doing it via merging as in #52 then we can either merge all out standing branches into all-wrappers and do the merge again or change base of them

**Comment by jenshnielsen** [comment]
That assumes that I am right in stating that no one else are using the master branch as is

**Comment by ThorvaldLarsen** [comment]
Solved by #52.
