### ISSUE TITLE
choosing plot save settings

### ISSUE THREAD

**Issue by nataliejpg** [qdev-dk/qdev-wrappers#46]
- now that we have the extension option to save png versions of the matplot can we make it an optional to save the qtplot versions as pngs (both seems overkill) or at least make them save in a subfolder to make things prettier?
- I was also wondering if it's possible the make the matplot pngs match the pdfs so if there is more than one plot per dataset they are saved with one image with all subplots and one individual one for each type?
@ThorvaldLarsen @Dominik-Vogel  thoughts?

**Comment by ThorvaldLarsen** [comment]
Definitely agree on the no qtplot png save. Qtplot is good to view the data but the figures are pretty ugly when saved.

It was a choice to not save individual png's for the matplot as I thought it just made unnecessary many files. Instead I run show_num when I need to save individual png's.
I dont feel too strongly about this choice and agree it would be nice if it has the same behaviour as the pdf's.

**Comment by nataliejpg** [comment]
I also recently had some problems in that it did not save the matplotlib versions when the plot finished. They were generated and saved if I ran show_num but not otherwise. I recognise that this is maybe not a good use of a developers time with the web ui hopefully coming soon but I wanted to report as a bug in the current plotting
