### ISSUE TITLE
vna extensions

### ISSUE THREAD

**Issue by nataliejpg** [qdev-dk/qdev-wrappers#48]
Following the discussion with @Dominik-Vogel and @ThorvaldLarsen I wrote these down so we wouldn't forget them and we can in some cases go ahead an implement and in others maybe discuss a bit.

- [x] make sure that when a non-spectroscopy channel is added all possible generators are deselected as generators on that channel and additionally set to have rf_off. At the moment it sets gen1 to be deselected but that's it.
- [x] when adding a spectroscopy channel the frequency and power of the readout channel should be set (either we should pick some default initial values or use some logic based on existing channels). At the moment when adding a generator the vna also tries to give it a frequency range which is outside the one possible by the R&S SGS100A which causes an error.
- [x] the parameters readout_freq and readout_pow shoudl belong to the spectroscopy channel and not the vna
- [x] is there a way to get it to show all channels in the display when you add one (ie same as pressing 'display' -> 'split' - > 'dual')?
- [x] can we overwrite the 'write' function to add a wait of 0.2 seconds after writing every command
- [x] setMagCav should only exist if a spectroscopy channel is present (and should also really be one per spectroscopy channel but for now maybe simpler just to have some sort of logic which checks for existance in the get function), also new name??
- [x] setMagCav should have settable max/min and detuning. I partially implemented this but it hasn't been tested. In the medium term these should be parameters

**Comment by ThorvaldLarsen** [comment]
After doing more automated stuff with VNA and alazar combined I have started wondering if setCav should be part of the VNA driver.

If it is possible to add some analysis between each measurement during a do1d (maybe qc.loop.task() can do stuff like this) then we can add it when setting up the scan rather than inside the VNA driver. This would also allow to set f.ex. the qubit frequency on a SGS100A with data taken by the VNA during a single qc.loop run.

At T11 I am literally running 4 do0d's in a for loop 60 times each to acces data for minor data analysis in between each do0d. Afterwards I then have to combine these 240 scans into 4 plots with 60 points.

**Comment by nataliejpg** [comment]
the fun thing is that it isn't really possible to do this in between measurements in a loop. You can use the python for loop but not the qcodes loop for this. Perhaps the answer is just to hang in until the new dataset arrives and do it then if its too messy to do it now. Maybe doing them separately and combining is the answer as it is obviously more adaptable and I realised that I don't think that 'readout_freq' would actually get stored at every point unless you also explicitly measured it. I'm not sure. Anyway I would be fine with this but could I get your code for combining plots (and maybe we can make it quite general and robust in the meantime while we wait for the new dataset)?

**Comment by ThorvaldLarsen** [comment]
If it isn't possible to do with qc.loop then we should keep setCav for now. It is a very convenient function.
The problem arrived when I wanted to do Rabi and T1 using data from the VNA spectroscopy.

**Comment by nataliejpg** [comment]
tell me about it.

**Comment by ThorvaldLarsen** [comment]
We now have a qc.Task that does the job of setCav in a much more transparent. I think we should remove setCav from the VNA driver.

However, I am not sure how best to introduce qc.Task into qdev-wrappers.

**Comment by nataliejpg** [comment]
that's great and thanks for the code @ThorvaldLarsen . I am making a sort of first draft of a qubit object and a measurement object just to have some sort of structure and I'll send it when I'm done. I feel like the kind of thing you describe should either be a function in transmon folder (basically a doXd_track_cav or sth) which would set up the loop and then call the same functions as doXd so the plotting would look the same etc or perhaps when we have some sort of infrastructure for qubit characterisation it should be a function belonging to one of these objects (although I am inclined to think it should be a standalone so that it can be used separately from qubit characterisation).

**Comment by ThorvaldLarsen** [comment]
I don't think these tasks should in any yaw touch the doXd's. As it is you can just add them as if they are measurements. This will keep stuff as separated as possible but also very flexible. I will send my code for automated qubit measurement on slack.

Sounds great with a  qubit object!
