### ISSUE TITLE
QDac numbering

### ISSUE THREAD

**Issue by ThorvaldLarsen** [qdev-dk/qdev-wrappers#50]
There is a bug with the numbering of channels on Qdac. Python starts counting channels at 0 while the channel outputs on the qdac are named 01-48.

So when setting in the config file 0 = name, .... The qdac output channel set by this line is Ch01.

**Comment by Dominik-Vogel** [comment]
good that you found that bug! this is probably very dangerous. Pleas let everybody know!

**Comment by ThorvaldLarsen** [comment]
Anyone using the qdac with the new driver will already have found out.
