### ISSUE TITLE
No port setting in StationConfigurator

### ISSUE THREAD

**Issue by emartinez** [qdev-dk/qdev-wrappers#85]
StationConfigurator doesn't import port settings from the configuration file, required for e.g. the magnets (qcodes.instrument_drivers.american_magnetics.AMI430). Proposed minimal fix: add
```
if 'port' in instr_cfg:
    init_kwargs['port'] = instr_cfg['port']
```
right after
```
if 'address' in instr_cfg:
    init_kwargs['address'] = instr_cfg['address']
```

**Comment by ThorvaldLarsen** [comment]
@emartinez you can put the port number in the init part of the yaml file:
`address: your address
    init:
        port: your port`

The `init` part is given as arguments when the instrument is initialised - that is `init` defines the dictionary `init_kwargs` which `address` is explicitly added to. `address` could also be moved down to the init part of the yaml file with same result.

**Comment by WilliamHPNielsen** [comment]
@ThorvaldLarsen great answer!
