### ISSUE TITLE
Liveplotting with figures in 2 rows

### ISSUE THREAD

**Issue by ThorvaldLarsen** [qdev-dk/qdev-wrappers#87]
Moving towards more and more parallel measurements it would be nice to have liveplotting done with the plots in two rows (or three). Doing measurements with 12 plots atm and gets pretty hard to see them all with them on one line.

If we dont fix it here it would be good to keep in mind for a future update to liveplotting in qcodes.

**Comment by nataliejpg** [comment]
justy flagging that this will have huge overlap with #47 so if one of them gets solved probably both of them do :)

**Comment by jenshnielsen** [comment]
qcplot does this so I think yes
