### ISSUE TITLE
Png save fails for sweep with many measurements (~8 or more)

### ISSUE THREAD

**Issue by ThorvaldLarsen** [qdev-dk/qdev-wrappers#88]
```
2018-04-22 18:58:28,331 - qdev_wrappers.sweep_functions - ERROR - Exception in doND
Traceback (most recent call last):
 File "C:\Users\t3user\qdev-wrappers\qdev_wrappers\sweep_functions.py", line 167, in _do_measurement
   _do_MatPlot(data,meas_params)
 File "C:\Users\t3user\qdev-wrappers\qdev_wrappers\sweep_functions.py", line 188, in _do_MatPlot
   plot.fig.tight_layout(pad=3)
 File "C:\Users\t3user\Anaconda3\envs\qcodes\lib\site-packages\matplotlib\figure.py", line 1755, in tight_layout
   self.subplots_adjust(**kwargs)
 File "C:\Users\t3user\Anaconda3\envs\qcodes\lib\site-packages\matplotlib\figure.py", line 1633, in subplots_adjust
   ax.update_params()
 File "C:\Users\t3user\Anaconda3\envs\qcodes\lib\site-packages\matplotlib\axes\_subplots.py", line 114, in update_params
   return_all=True)
 File "C:\Users\t3user\Anaconda3\envs\qcodes\lib\site-packages\matplotlib\gridspec.py", line 429, in get_position
   gridspec.get_grid_positions(fig)
 File "C:\Users\t3user\Anaconda3\envs\qcodes\lib\site-packages\matplotlib\gridspec.py", line 90, in get_grid_positions
   subplot_params = self.get_subplot_params(fig)
 File "C:\Users\t3user\Anaconda3\envs\qcodes\lib\site-packages\matplotlib\gridspec.py", line 376, in get_subplot_params
   hspace=hspace)
 File "C:\Users\t3user\Anaconda3\envs\qcodes\lib\site-packages\matplotlib\figure.py", line 193, in __init__
   self.update(left, bottom, right, top, wspace, hspace)
 File "C:\Users\t3user\Anaconda3\envs\qcodes\lib\site-packages\matplotlib\figure.py", line 228, in update
   raise ValueError('left cannot be >= right')
ValueError: left cannot be >= right
```

**Comment by ThorvaldLarsen** [comment]
I think it is due to a scalling of the figure size. Maybe it does not take colorbar into account when deciding the size of the figure.

**Comment by ThorvaldLarsen** [comment]
@Dominik-Vogel Not sure who would be the right one to look into this but is it possible that we can bump this up on the priority list?

**Comment by Dominik-Vogel** [comment]
@ThorvaldLarsen I could not reproduce the error. Could you contact me, that we can figure out what is happening?

**Comment by ThorvaldLarsen** [comment]
Hmm.. weird. Did you try colorplots? Maybe it's due to the colorbars.

**Comment by Dominik-Vogel** [comment]
By colorplots you mean heatmap type (2d) plots?

**Comment by Dominik-Vogel** [comment]
ok with heatmap type plots I get the same error. I'll try to fix it.

**Comment by jenshnielsen** [comment]
@Dominik-Vogel  I think this is likely to be a bug in matplotlib. I think the tight layout eventually tries to get the figure small enough that it ends up with a negative width, we should try upgrading to the latest matplotlib and see if that works

**Comment by ThorvaldLarsen** [comment]
@Dominik-Vogel @jenshnielsen Just tried with matplotlib version 2.2.2 and got same error. After digging a bit more I found the issue. The figure size in qcodes.plots.qcmatplotlib.py is defined by the function:
```
def default_figsize(subplots):
        """
        Provides default figsize for given subplots.
        Args:
            subplots (Tuple[Int, Int]): shape (nrows, ncols) of subplots

        Returns:
            Figsize (Tuple[Float, Float])): (width, height) of default figsize
              for given subplot shape
        """
        if not isinstance(subplots, tuple):
            raise TypeError('Subplots {} must be a tuple'.format(subplots))
        return (min(3 + 3 * subplots[1], 12), 1 + 3 * subplots[0])
```
The `min` function ensures that the maximum suze of the figure is 12. Of course as some point this is not large enough to contain all the elements. Is there a reason for this any reason for this `min` function instead of just letting the size scale?

Changing the last line to `return (3 + 3 * subplots[1], 1 + 3 * subplots[0])` does indeed solve the problem.

**Comment by ThorvaldLarsen** [comment]
The aspect ratio does get pretty large for the figure but I think this should rather be solve by making qdev-wrappers create plots with more rows.

**Comment by Dominik-Vogel** [comment]
@ThorvaldLarsen agreed, this should not cause us any problems. I suggest in the meantime to set a standard value for the max aspect ratio in the config. Jenses explanation seems very convincing.

**Comment by ThorvaldLarsen** [comment]
Out of curiosity: why do we need a max aspect ratio? That is what we have at the moment which caused this error.

I don't think this is due to a bug. To me it seems that `tight_layout` only scales the data part of the subplot but leaves axis labels and colorbars at fixed size (e.g. font sizes are not changed). So when there isn't room enough for these it tries to make negatively sized subplots.
Same issue here: https://stackoverflow.com/questions/49042462/how-to-fix-plt-tight-layout-error-while-plotting-multiple-heatmaps

**Comment by ThorvaldLarsen** [comment]
@Dominik-Vogel @jenshnielsen just FYI: qcodes MatPlot fails for interrupted scans with matplotlib version 2.2.2 due to a change in handling of MaskedArrays https://github.com/matplotlib/matplotlib/pull/9723.  pcolormesh throws this error: `ValueError: x and y arguments to pcolormesh cannot have non-finite values or be of type numpy.ma.core.MaskedArray with masked values` when trying to plot the data.

**Comment by ThorvaldLarsen** [comment]
@Dominik-Vogel @jenshnielsen Any chance we could get this fixed in near future? I think @nataliejpg would also be very interested in this as they are starting to measure on T2 soon.
